### PR TITLE
Update name of the repo

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Ref: https://github.com/cryptnono/cryptnono/issues/26

Not sure if this is the only thing needed. As @manics mentioned in the issue above, this might just fix it for new tags?

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
Ah, I didn't meant to open from this branch 🙄 sorry for the noise

**Comment by yuvipanda** [comment]
@GeorgianaElena i think we still need this too, along with https://github.com/cryptnono/cryptnono/pull/27 and https://github.com/cryptnono/cryptnono/pull/29?

**Comment by GeorgianaElena** [comment]
Ah, yes! I had one local branch that that all changes 😄

**Comment by yuvipanda** [comment]
Thanks @GeorgianaElena and sorry for the trouble!

**Pull request merged**
